[package]
name = "pjson"
version = "0.1.2"
authors = ["Josh Baker <joshbaker77@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/tidwall/pjson.rs"
documentation = "https://docs.rs/pjson/"
description = "JSON stream parser"

[dependencies]
